---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 10001
eureka:
  instance:
    hostname: localhost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/